# Generated by Django 5.0.3 on 2024-06-01 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_alter_customuser_indexno_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
