# Generated by Django 5.0.3 on 2024-06-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0006_remove_profile_user_delete_customuser_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ID', 'ID'), ('Personal Belongings', 'Personal Belongings'), ('Devices', 'Devices')], max_length=100)),
                ('image', models.ImageField(upload_to='lost_images/')),
                ('lostdesc', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('indexNo', models.IntegerField()),
                ('location', models.TextField()),
            ],
        ),
    ]
