# Generated by Django 5.0.3 on 2024-07-02 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lost',
        ),
    ]
