# Generated by Django 5.0.3 on 2024-07-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='reviewer_name',
        ),
        migrations.AddField(
            model_name='review',
            name='uploader_name',
            field=models.TextField(default='unknown'),
            preserve_default=False,
        ),
    ]
