# Generated by Django 5.0.3 on 2024-07-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0011_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badges',
            name='uploader_name',
            field=models.CharField(max_length=255),
        ),
    ]
