# Generated by Django 5.0.3 on 2024-08-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0012_alter_badges_uploader_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='category',
            field=models.CharField(choices=[('ID', 'ID'), ('Wallet', 'Wallet'), ('Keys', 'Keys'), ('Phone', 'Phone'), ('Laptop', 'Laptop'), ('Tablet', 'Tablet'), ('Clothing', 'Clothing'), ('Jewelry', 'Jewelry'), ('Backpack', 'Backpack'), ('Headphones', 'Headphones'), ('Glasses', 'Glasses'), ('Books', 'Books'), ('Documents', 'Documents'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lost',
            name='indexNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lost',
            name='lostdesc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lost',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
